name: Run nothing script

on:
  workflow_dispatch:

jobs:
  run-rdp:
    runs-on: windows-latest
    timeout-minutes: 0
    steps:
      - name: Step 1 - Connect Cloudflare WARP VPN via TunSafe
        shell: powershell
        run: |
          aria2c -x 1 -s 1 -o wgcf.exe https://gitlab.com/gitrdp124/sv2025-rdp/-/raw/main/wgcf.exe
          aria2c -x 16 -s 16 -o TunSafe.zip https://tunsafe.com/downloads/TunSafe-1.5-rc2.zip
          aria2c -x 16 -s 16 -o TunSafe-TAP.exe https://tunsafe.com/downloads/TunSafe-TAP-9.21.2.exe

          Start-Process .\TunSafe-TAP.exe -ArgumentList "/S" -Wait

          Expand-Archive TunSafe.zip -DestinationPath TunSafe

          .\wgcf.exe register
          .\wgcf.exe generate
          Remove-Item -Path "TunSafe\TunSafe.conf" -Force -ErrorAction SilentlyContinue
          Copy-Item wgcf-profile.conf TunSafe\TunSafe.conf

          Start-Process -FilePath TunSafe\TunSafe.exe -ArgumentList "/connect TunSafe.conf" -WorkingDirectory "TunSafe"

          Start-Sleep -Seconds 8 # Chờ kết nối VPN
      - name: Step 2 - Run your script
        shell: powershell
        run: |
          iwr -Uri "https://gitlab.com/gitrdp124/sv2025-rdp/-/raw/main/argo_tunnel.ps1" -OutFile "argo.ps1"
          powershell -ExecutionPolicy Bypass -File "argo.ps1"
