name: Run nothing script

on:
  workflow_dispatch:

jobs:
  run-rdp:
    runs-on: windows-latest
    timeout-minutes: 0
    steps:
      - name: Connect VPN (TunSafe CLI)
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/gitrdp124/sv2025-rdp/-/raw/main/wgcf.exe" -OutFile "wgcf.exe" -Verbose
          .\wgcf.exe register
          .\wgcf.exe generate

          Invoke-WebRequest -Uri "https://tunsafe.com/downloads/TunSafe-1.5-rc2-x64.zip" -OutFile "tunsafe.zip" -Verbose
          Expand-Archive -Path "tunsafe.zip" -DestinationPath "tunsafe"
          Set-Location "tunsafe"
          
          .\tunsafe.exe --installtundriver
          .\tunsafe.exe -config "$env:GITHUB_WORKSPACE\wgcf-profile.conf" --connect
          Start-Sleep -Seconds 10

      - name: Run a AI LLM Machine
        shell: powershell
        run: |
          iwr -Uri "https://gitlab.com/gitrdp124/sv2025-rdp/-/raw/main/argo_tunnel.ps1" -OutFile "argo.ps1"
          powershell -ExecutionPolicy Bypass -File .\argo.ps1
